import crypto from "node:crypto";
export const ROUTES={SCHOOL_HOMEWORK:"homework_quest",SCHOOL_READINESS:"control_centre.school_readiness",CONTACTS:"control_centre.contacts_services",REPAIRS:"control_centre.repairs",SHOPPING:"control_centre.shopping_radar",FOOD:"control_centre.food_meal_planner",EVENTS:"control_centre.calendar_events",ADMIN:"control_centre.personal_admin",PETS:"control_centre.pet_care",ELECTRICITY:"control_centre.electricity",REVIEW:"review_queue"};
export function normalisePayload(input={}){const text=String(input.text??"").trim();const attachments=Array.isArray(input.attachments)?input.attachments:[];return{source_type:input.source_type||"whatsapp_share",source_chat:input.source_chat||null,sender:input.sender||null,source_timestamp:input.source_timestamp||null,text,attachments,content_types:[...new Set([...(text?["text"]:[]),...attachments.map(a=>a?.mime_type||a?.type||"file")])],raw_evidence_ref:input.raw_evidence_ref||null,client_context:input.client_context||null};}
export function fingerprint(payload){const canonical=JSON.stringify({source_type:payload.source_type,source_chat:payload.source_chat,sender:payload.sender,source_timestamp:payload.source_timestamp,text:payload.text,attachments:payload.attachments.map(a=>({name:a?.name||null,mime_type:a?.mime_type||a?.type||null,size:a?.size||null,sha256:a?.sha256||null}))});return crypto.createHash("sha256").update(canonical).digest("hex");}
const hasAny=(t,words)=>words.some(w=>t.includes(w));
function inferSchool(t,chat=""){const s=(t+" "+chat).toLowerCase();if(hasAny(s,["pnps","pinelands north primary"]))return"PNPS";if(hasAny(s,["red roots"]))return"Red Roots";if(hasAny(s,["100 acre wood","100acrewood","haw"]))return"100 Acre Wood";return null;}
function inferChildren(t,school){const names=[];if(/\bharrison\b/i.test(t))names.push("Harrison");if(/\balexander\b|\balex\b/i.test(t))names.push("Alexander");if(/\bimogen\b/i.test(t))names.push("Imogen");if(!names.length&&school==="100 Acre Wood")names.push("Imogen");return names;}
export function classify(payload){const t=payload.text.toLowerCase(),routes=[],reasons=[];let confidence=.45;const schoolName=inferSchool(t,payload.source_chat||"");const schoolContext=!!schoolName||hasAny(t,["school","teacher","class","grade r","homework","huiswerk"]);const homework=hasAny(t,["homework","huiswerk","spelling","reading","lees","maths","wiskunde","worksheet","revise","hersien","klanke","phonics","sight words","pages ","page "]);const readiness=hasAny(t,["civvies","uniform","sports kit","library bag","library book","bring","wear","shirt","money"," r","form","permission","consent","project","themed","bokke","springbok","raffle","photo order"]);const event=hasAny(t,["tomorrow","monday","tuesday","wednesday","thursday","friday","saturday","sunday","deadline","due ","rsvp","at 0","at 1","at 2","at 3","save the date"]);
if(schoolContext&&homework){routes.push(ROUTES.SCHOOL_HOMEWORK);reasons.push("school homework/learning task");confidence=Math.max(confidence,.9);}
if(schoolContext&&readiness){routes.push(ROUTES.SCHOOL_READINESS);reasons.push("school readiness/parent action");confidence=Math.max(confidence,.9);}
if(schoolContext&&event){routes.push(ROUTES.EVENTS);reasons.push("school item contains date/day/deadline candidate");confidence=Math.max(confidence,.78);}
if(hasAny(t,["plumber","electrician","handyman","cleaner","cleaning","gardener","repair","fix","recommend","recommendation","contact number","whatsapp him","whatsapp her"])){routes.push(ROUTES.CONTACTS);reasons.push("service/contact recommendation");confidence=Math.max(confidence,.78);if(hasAny(t,["repair","fix","broken","leak","plumber","electrician","handyman"]))routes.push(ROUTES.REPAIRS);}
if(hasAny(t,["special","sale","deal","price","checkers","pick n pay","pnp","woolworths","food lover","dis-chem","clicks","takealot","temu"])){routes.push(ROUTES.SHOPPING);reasons.push("shopping/deal language");confidence=Math.max(confidence,.8);}
if(hasAny(t,["recipe","dinner","lunch","breakfast","meal","ingredients","vegan","vegetarian"])){routes.push(ROUTES.FOOD);reasons.push("food/meal language");confidence=Math.max(confidence,.72);}
if(!schoolContext&&hasAny(t,["invitation","invite","rsvp","appointment","meeting","party","concert","on saturday","on sunday","save the date"])){routes.push(ROUTES.EVENTS);reasons.push("event/date language");confidence=Math.max(confidence,.75);}
if(hasAny(t,["passport","home affairs","licence","license","id document","birth certificate","sars","municipal account"])){routes.push(ROUTES.ADMIN);reasons.push("personal admin language");confidence=Math.max(confidence,.82);}
if(hasAny(t,["vet","vaccine","vaccination","dog","cat","pet","rescue","groomer"])){routes.push(ROUTES.PETS);reasons.push("pet-care language");confidence=Math.max(confidence,.75);}
if(hasAny(t,["meter reading","electricity meter","kwh","prepaid electricity"])){routes.push(ROUTES.ELECTRICITY);reasons.push("electricity language");confidence=Math.max(confidence,.9);}
const unique=[...new Set(routes)];return{routes:(!unique.length||confidence<.6)?[ROUTES.REVIEW]:unique,confidence,reasons:reasons.length?reasons:["no sufficiently confident route"],school:schoolName,children:inferChildren(payload.text,schoolName)};}
export function buildRecord(input,now=new Date()){const payload=normalisePayload(input),source_id=fingerprint(payload),routing=classify(payload);return{source_id,source_type:payload.source_type,received_at:now.toISOString(),source_chat:payload.source_chat,sender:payload.sender,source_timestamp:payload.source_timestamp,content_types:payload.content_types,raw_evidence_ref:payload.raw_evidence_ref,text:payload.text,attachments:payload.attachments,extracted:{school:routing.school,children:routing.children},routes:routing.routes,confidence:routing.confidence,routing_reasons:routing.reasons,status:routing.routes.includes(ROUTES.REVIEW)?"needs_review":"routed"};}