import type { Config } from "@netlify/functions";
import { getStore,getDeployStore } from "@netlify/blobs";
import { timingSafeEqual } from "node:crypto";
import { buildRecord } from "./core.mjs";
import { prepareEvidence } from "./attachments.mjs";
import { newCapability,handoffKey,createHandoffRecord } from "./handoff-core.mjs";
import { destinationSummary,shortcutMessage,nextActions,choosePrimaryAction,recoveryState,handoffStatus,shortcutPlan } from "./orchestration.mjs";
import { ensureRouteOutbox,pendingRoutesFromEnsure } from "./outbox-core.mjs";
function storeForEnvironment(){return Netlify.context?.deploy?.context==="production"?getStore("familyroy-intake",{consistency:"strong"}):getDeployStore({name:"familyroy-intake",consistency:"strong"});}
function authorised(req:Request){const expected=Netlify.env.get("FAMILYROY_INTAKE_TOKEN")||"";const supplied=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!expected||!supplied)return false;const a=Buffer.from(expected),b=Buffer.from(supplied);return a.length===b.length&&timingSafeEqual(a,b);}
function validBody(body:any){return body&&typeof body==="object"&&(String(body.text??"").trim().length>0||(Array.isArray(body.attachments)&&body.attachments.length>0)||(body.payload&&typeof body.payload==="object"&&String(body.payload.data_base64??"").trim().length>0));}
async function issueHandoffs(store:any,record:any,pendingRoutes=new Set()){const browserRoutes=new Set(["homework_quest","control_centre.school_readiness"]),handoffs:any={};for(const route of record.routes||[]){if(!browserRoutes.has(route)||!pendingRoutes.has(route))continue;const capability=newCapability(),h=createHandoffRecord({token:capability,route,source_id:record.source_id});await store.setJSON(handoffKey(capability),h);handoffs[route]={capability,expires_at:h.expires_at,delivery:"scoped_handoff"};}return handoffs;}
function result(record:any,duplicate:boolean,handoffs:any={},endpoint=""){const actions=nextActions(record.routes,handoffs),message=shortcutMessage({duplicate,status:record.status,routes:record.routes,handoffs}),primary=choosePrimaryAction(actions),plan=shortcutPlan({shortcut_message:message,primary_action:primary},{intake_endpoint:endpoint,homework_quest:Netlify.env.get("FAMILYROY_HOMEWORK_URL")||"","control_centre.school_readiness":Netlify.env.get("FAMILYROY_CONTROL_CENTRE_URL")||""}),primaryAction=primary?{...primary,launch_url:plan.open_url}:null;return{ok:true,duplicate,source_id:record.source_id,status:record.status,routes:record.routes,confidence:record.confidence??null,extracted:record.extracted??null,handoffs,destinations:destinationSummary(record.routes,handoffs),next_actions:actions,primary_action:primaryAction,launch_url:plan.open_url,handoff_status:handoffStatus(record.routes,handoffs),recovery:recoveryState({status:record.status,duplicate,next_actions:actions}),shortcut_message:message};}
export default async(req:Request)=>{if(req.method!=="POST")return new Response("Method Not Allowed",{status:405,headers:{Allow:"POST"}});if(!authorised(req))return Response.json({ok:false,error:"unauthorized",shortcut_message:"FamilyRoy authentication failed"},{status:401});let body:any;try{body=await req.json();}catch{return Response.json({ok:false,error:"invalid_json",shortcut_message:"FamilyRoy could not read this share"},{status:400});}if(!validBody(body))return Response.json({ok:false,error:"empty_evidence",shortcut_message:"Nothing useful was shared"},{status:422});let prepared:any;try{prepared=prepareEvidence(body);}catch(e:any){const code=e?.message||"invalid_attachment";const status=code==="attachment_too_large"?413:422;return Response.json({ok:false,error:code,shortcut_message:code==="attachment_too_large"?"That file is too large for FamilyRoy":"FamilyRoy could not read that attachment"},{status});}const record=buildRecord(prepared);const store=storeForEnvironment();for(const item of prepared._evidence||[]){await store.set(`evidence/${record.source_id}/${item.meta.sha256}`,item.bytes,{metadata:{name:item.meta.name,mime_type:item.meta.mime_type}});}const key=`sources/${record.source_id}.json`;const existing=await store.get(key,{type:"json"});if(existing){const ensured=await ensureRouteOutbox(store,existing,{repairOnly:true}),pending=pendingRoutesFromEnsure(ensured),handoffs=await issueHandoffs(store,existing,pending);return Response.json(result(existing,true,handoffs,new URL(req.url).origin));}await store.setJSON(key,record);const ensured=await ensureRouteOutbox(store,record),pending=pendingRoutesFromEnsure(ensured),handoffs=await issueHandoffs(store,record,pending);return Response.json(result(record,false,handoffs,new URL(req.url).origin),{status:201});};
export const config:Config={path:"/intake"};