import test from "node:test";
import assert from "node:assert/strict";
import {buildCalendarReview,calendarDecision,shouldConsumeCalendarOutbox} from "../netlify/functions/calendar-review-core.mjs";
const source="a".repeat(64),ref=new Date("2026-10-06T12:00:00+02:00");
function item(candidate){return{source_id:source,route:"control_centre.calendar_events",created_at:"2026-10-06T10:00:00Z",payload:{source_id:source,source_type:"whatsapp_share",source_chat:"PNPS",text:candidate.source_text||candidate.title,event_candidate:candidate,evidence:[{sha256:"abc"}]}};}
test("review preserves evidence and source identity",()=>{const x=buildCalendarReview(item({title:"Sports day",date_text:"23 October 2026",time_text:"17:30",source_text:"Sports day on 23 October 2026 at 17:30."}),ref);assert.equal(x.source_id,source);assert.equal(x.source.evidence[0].sha256,"abc");assert.equal(x.status,"ready");});
test("relative date review remains confirmation-required",()=>{const x=buildCalendarReview(item({title:"Bring bag",date_text:"Friday",source_text:"Bring bag Friday"}),ref);assert.equal(x.status,"needs_confirmation");assert.match(x.dedupe_key,/calendar:friday:all-day$/);});
test("confirm emits a destination event only after decision",()=>{const x=buildCalendarReview(item({title:"Sports day",date_text:"23 October 2026",time_text:"17:30"}),ref),d=calendarDecision(x,"confirm");assert.equal(d.state,"confirmed");assert.equal(d.event.title,"Sports day");assert.equal(d.event.alerts.length,2);assert.equal(shouldConsumeCalendarOutbox(d),true);});
test("review edits can safely resolve an ambiguous candidate",()=>{const x=buildCalendarReview(item({title:"Bring bag",date_text:"Friday"}),ref),d=calendarDecision(x,"confirm",{start_local:"2026-10-09T00:00:00",all_day:true,alerts:[{offset_minutes:-540}]});assert.equal(d.state,"confirmed");assert.equal(d.event.start_local,"2026-10-09T00:00:00");});
test("reject is terminal and consumes without creating an event",()=>{const x=buildCalendarReview(item({title:"Noise",date_text:"Friday"}),ref),d=calendarDecision(x,"reject");assert.equal(d.state,"rejected");assert.equal(d.event,undefined);assert.equal(shouldConsumeCalendarOutbox(d),true);});
test("invalid decision leaves outbox pending",()=>{const x=buildCalendarReview(item({title:"Thing",date_text:"Friday"}),ref),d=calendarDecision(x,"later");assert.equal(d.ok,false);assert.equal(shouldConsumeCalendarOutbox(d),false);});
