import test from "node:test";import assert from "node:assert/strict";import{buildRecord,classify,fingerprint,normalisePayload,ROUTES}from"../netlify/functions/core.mjs";
test("same input has same fingerprint",()=>{const a=normalisePayload({text:"Bring R20 for school on Friday",source_chat:"PNPS"});assert.equal(fingerprint(a),fingerprint(a));});
test("PNPS homework multi-routes homework readiness and event",()=>{const r=buildRecord({source_chat:"PNPS Parents",text:"Alexander: homework is revise klanke. Bring library bag on Friday."});assert.ok(r.routes.includes(ROUTES.SCHOOL_HOMEWORK));assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));assert.ok(r.routes.includes(ROUTES.EVENTS));assert.ok(!r.routes.includes(ROUTES.SHOPPING));assert.equal(r.extracted.school,"PNPS");assert.deepEqual(r.extracted.children,["Alexander"]);});
test("HAW context safely infers Imogen",()=>{const r=buildRecord({source_chat:"100 Acre Wood",text:"Please bring the permission form tomorrow"});assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));assert.equal(r.extracted.school,"100 Acre Wood");assert.deepEqual(r.extracted.children,["Imogen"]);});
test("does not guess child for generic PNPS message",()=>{const r=buildRecord({source_chat:"PNPS",text:"Civvies on Friday"});assert.deepEqual(r.extracted.children,[]);});
test("service recommendation routes to contacts and repairs",()=>{const r=buildRecord({text:"Can recommend a great plumber to fix the leaking tap. WhatsApp him."});assert.ok(r.routes.includes(ROUTES.CONTACTS));assert.ok(r.routes.includes(ROUTES.REPAIRS));});
test("ambiguous text goes to review",()=>{const r=buildRecord({text:"This looks useful"});assert.deepEqual(r.routes,[ROUTES.REVIEW]);});
test("Red Roots homework routes correctly",()=>{const r=buildRecord({source_chat:"Red Roots",text:"Homework: reading and sight words"});assert.ok(r.routes.includes(ROUTES.SCHOOL_HOMEWORK));assert.equal(r.extracted.school,"Red Roots");});
test("school readiness can exist without homework",()=>{const r=buildRecord({source_chat:"PNPS",text:"Bokke shirts and civvies on Friday. Bring R20."});assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));assert.ok(!r.routes.includes(ROUTES.SCHOOL_HOMEWORK));});
test("school event candidate multi-routes without inventing a child",()=>{const r=buildRecord({source_chat:"PNPS",text:"Please return the consent form by Tuesday"});assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));assert.ok(r.routes.includes(ROUTES.EVENTS));assert.deepEqual(r.extracted.children,[]);});
test("PnP shopping shorthand still routes to Shopping Radar",()=>{const r=buildRecord({text:"PnP special on oat milk this week"});assert.ok(r.routes.includes(ROUTES.SHOPPING));});

test("school information alone does not become readiness",()=>{const r=buildRecord({source_chat:"PNPS",text:"Please note the library will be closed on Friday."});assert.ok(!r.routes.includes(ROUTES.SCHOOL_READINESS));});
test("optional school participation does not become readiness",()=>{const r=buildRecord({source_chat:"PNPS",text:"Parents may buy raffle tickets if they wish on Friday."});assert.ok(!r.routes.includes(ROUTES.SCHOOL_READINESS));});
test("concrete physical school obligation becomes readiness",()=>{const r=buildRecord({source_chat:"PNPS",text:"Please ensure Harrison brings his library book on Friday."});assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));assert.ok(r.routes.includes(ROUTES.EVENTS));});
test("fee notice does not leak into readiness",()=>{const r=buildRecord({source_chat:"Red Roots",text:"Please note the 2027 school fee structure is attached and payment is due Friday."});assert.ok(!r.routes.includes(ROUTES.SCHOOL_READINESS));});
test("homework can route without physical readiness",()=>{const r=buildRecord({source_chat:"PNPS",text:"Harrison homework: practise spelling words 1 to 10."});assert.ok(r.routes.includes(ROUTES.SCHOOL_HOMEWORK));assert.ok(!r.routes.includes(ROUTES.SCHOOL_READINESS));});
test("mixed learning and packing multi-routes",()=>{const r=buildRecord({source_chat:"PNPS",text:"Homework: read page 12. Pack the library bag for Friday."});assert.ok(r.routes.includes(ROUTES.SCHOOL_HOMEWORK));assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));assert.ok(r.routes.includes(ROUTES.EVENTS));});
test("generic due metadata is not enough for readiness",()=>{const r=buildRecord({source_chat:"PNPS",text:"Due Date: 3 Sep 2026"});assert.ok(!r.routes.includes(ROUTES.SCHOOL_READINESS));});

test("mixed school share builds separate downstream payloads from one source",()=>{const r=buildRecord({source_type:"whatsapp_share",source_chat:"PNPS",text:"Harrison homework: read page 12. Bring library bag on Friday."});assert.equal(r.route_payloads[ROUTES.SCHOOL_HOMEWORK].mode,"import_candidate");assert.equal(r.route_payloads[ROUTES.SCHOOL_HOMEWORK].fidelity,"preserve_source");assert.equal(r.route_payloads[ROUTES.SCHOOL_READINESS].mode,"parse_readiness");assert.equal(r.route_payloads[ROUTES.SCHOOL_READINESS].dedupe_key,r.source_id);assert.equal(r.route_payloads[ROUTES.EVENTS].mode,"extract_event_candidate");});
test("review queue preserves original evidence context",()=>{const r=buildRecord({source_type:"manual",text:"This looks useful"});assert.equal(r.route_payloads[ROUTES.REVIEW].mode,"human_review");assert.equal(r.route_payloads[ROUTES.REVIEW].text,"This looks useful");});

test("please note does not suppress a concrete readiness obligation",()=>{const r=classify(normalisePayload({text:"PNPS. Please note: please bring Harrison's library book on Friday."}));assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));});
test("learning verb with library book is Homework only, not physical readiness",()=>{const r=classify(normalisePayload({text:"PNPS homework: Harrison must read the library book."}));assert.ok(r.routes.includes(ROUTES.SCHOOL_HOMEWORK));assert.ok(!r.routes.includes(ROUTES.SCHOOL_READINESS));});
test("optional item does not suppress a separate strong obligation",()=>{const r=classify(normalisePayload({text:"PNPS: Parents may buy raffle tickets. Please return Alexander's consent form on Friday."}));assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));});

test("informational paragraph does not suppress a separate concrete obligation",()=>{const r=buildRecord({source_chat:"PNPS",text:"Newsletter: the library will be closed next week. Please return Harrison's library book on Friday."});assert.ok(r.routes.includes(ROUTES.SCHOOL_READINESS));assert.ok(r.routes.includes(ROUTES.EVENTS));});
